# image: python:3.6-alpine - Remove dependecies
image: python:3.8-slim-buster
  
stages:
  - build
  - test
  - deploy

before_script:
   # - apk update && apk add gcc python3-dev musl-dev libffi-dev
   - pip install --upgrade pip
   - pip install twine
   - python setup.py sdist bdist_wheel

test_job:
  stage: test
  script:
    - echo "Running tests"
    - python -m unittest discover -s "./tests/"


deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
